Fixed signRequest method, ID_FORMAT and OBJECTID_EXTRACTOR regex
EMCECS/atmos-dotnet pull request #10
Opened 2022-01-17 10:55 UTC by polinello

Fixed signRequest method: include custom headers in the signature header. Fixed ID_FORMAT and OBJECTID_EXTRACTOR regex in order to avoid cutting bug

2022-01-17 20:03 UTC, xiaoxin-ren reviewed
Thanks very much for submitting the PR, I included questions in comments, just to make sure we'll get to a general fix.

2022-01-19 02:47 UTC, twincitiesguy commented on EsuApiLib/ObjectId.cs
> +        private static readonly Regex ID_FORMAT = new Regex("^[0-9a-f-]{44,}$");
We should always use the OID returned in the original POST (create) header response to identify that object.  In this case, it will be the longer format.

2022-01-19 02:49 UTC, twincitiesguy commented on EsuApiLib/Rest/EsuRestApi.cs
> +            // Include custom headers in the signature header [Added to solve custom headers bug]
I agree that we need a test case for custom x-emc headers

2022-01-19 03:04 UTC, twincitiesguy requested changes
The `IndexOf` call should be case-insensitive - maybe lowercase the `key` first.

2022-01-19 03:04 UTC, twincitiesguy commented on EsuApiLib/ObjectId.cs
> +        private static readonly Regex ID_FORMAT = new Regex("^[0-9a-f-]{44,}$");
We should always use the OID returned in the original POST (create) header response to identify that object. In this case, it will be the longer format.

2022-01-19 03:04 UTC, twincitiesguy commented on EsuApiLib/Rest/EsuRestApi.cs
> +            // Include custom headers in the signature header [Added to solve custom headers bug]
I agree that we need a test case for custom x-emc headers

2022-01-27 14:53 UTC, closed without merging