Fix Object ID format to be compatible to ECS Atmos
EMCECS/atmos-dotnet pull request #12
Opened 2022-02-07 15:13 UTC by xiaoxin-ren

1. Fix EsuApiTest build failure in VS2019.
2. Fix Object ID format to be compatible to ECS Atmos.

2022-02-09 21:04 UTC, twincitiesguy requested changes
`MetadataList` is for user metadata.  To add headers, given the SDK design, we will need to modify the appropriate methods that accept these new headers and add them.  Then re-add the previous method signature to maintain compatibility.

2022-02-10 09:57 UTC, xiaoxin-ren commented on EsuApiLib/Rest/EsuRestApi.cs
> +                    if (meta.Name == "x-emc-expiration-period" || meta.Name == "x-emc-retention-period") {
Explained as above. .NET version is less OO comparing to Java version. `CustomHeaders ` is intended for 3rd party headers(.e.g auth proxy), and not a good place for native x-emc headers.

2022-02-10 18:12 UTC, twincitiesguy commented on EsuApiLib/Rest/EsuRestApi.cs
> +                    if (meta.Name == "x-emc-expiration-period" || meta.Name == "x-emc-retention-period") {
Based on our zoom discussion, I think we have a good approach - let's add these as properties to `MetadataList`.  That way, we don't need a bunch of new method permutations, and we don't hijack the user-metadata dictionary.

2022-02-11 15:43 UTC, twincitiesguy commented on EsuApiLib/MetadataList.cs
> +// Copyright ?2008, EMC Corporation.
Please make sure this is 2022 - the strange character may be due to your editor not using UTF-8 for the file

2022-02-11 15:45 UTC, twincitiesguy approved these changes

2022-02-11 17:58 UTC, merged